### ISSUE TITLE
add dummy chapters and content files

### ISSUE THREAD

**Issue by Edlingeer** [DanielSank/vankampen-stochastic#6]

**Comment by DanielSank** [comment]
Fixed via #8.

**Comment by Edlingeer** [comment]
I'm done merging my master branch with yours although it was kind of a
hustle especially since I'm not using git on a daily basis.

Cordialement,

Thomas NUSSLE

2016-05-31 4:41 GMT+02:00 Daniel Sank notifications@github.com:

**Comment by DanielSank** [comment]
@Edlingeer I apologize for the hustle. Next time I won't do anything to cause so many conflicts. It was my fault.

Thanks again for the pull request!

**Comment by Edlingeer** [comment]
No no, that's not what I meant at all, it's just that I'm not used to git
and having to deal with conflicts is not that easy for me because of that.
I'm not looking for anyone's fault in anything :) .

Cordialement,

Thomas NUSSLE

2016-06-02 19:01 GMT+02:00 Daniel Sank notifications@github.com:

**Comment by DanielSank** [comment]
Well, I still think the way I handled the merge made it harder for you than it had to be. We'll see next time :)
